# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [pre-commit, pre-merge-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit, pre-merge-commit, manual]
    -   id: end-of-file-fixer
        stages: [pre-commit, pre-merge-commit, manual]
        exclude: |
            (?x)^(
                docs/docs/SUMMARY.md|
                docs/docs/en/api/.meta.yml
            )$
    -   id: check-yaml
        stages: [pre-commit, pre-merge-commit, manual]
        exclude: 'docs/mkdocs.yml'
    -   id: check-added-large-files
        stages: [pre-commit, pre-merge-commit, manual]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        stages: [pre-commit, pre-merge-commit, manual]
        args: [--ignore-words=.codespell-whitelist.txt]
        exclude: |
            (?x)^(
                docs/overrides/home.html
            )$

-   repo: local
    hooks:
    -   id: lint
        name: Linter
        stages: [pre-commit, pre-merge-commit, manual]
        entry: "scripts/lint-pre-commit.sh"
        language: python
        types: [python]
        require_serial: true
        verbose: true

-   repo: local
    hooks:
    -   id: static-analysis
        name: Static analysis
        entry: "scripts/static-pre-commit.sh"
        language: python
        types: [python]
        require_serial: true
        verbose: true

-   repo: local
    hooks:
    -   id: docs
        name: Build docs
        entry: "scripts/build-docs-pre-commit.sh"
        language: python
        files: ^docs
        require_serial: true
        verbose: true

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
        stages: [pre-commit, pre-merge-commit, manual]
