# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: |
            (?x)^(
                docs/docs/SUMMARY.md|
                .faststream_gen/rabbit/ack.md|
                docs/docs/en/api/.meta.yml
            )$
    -   id: check-yaml
        exclude: 'docs/mkdocs.yml'
    -   id: check-added-large-files

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        args: [--ignore-words=.codespell-whitelist.txt]
        exclude: |
            (?x)^(
                docs/overrides/home.html
            )$

-   repo: local
    hooks:
    -   id: lint
        name: Linter
        entry: "scripts/lint-pre-commit.sh"
        language: python
        language_version: python3.8
        types: [python]
        require_serial: true
        verbose: true

-   repo: local
    hooks:
    -   id: static-analysis
        name: Static analysis
        entry: "scripts/static-pre-commit.sh"
        language: python
        language_version: python3.8
        types: [python]
        require_serial: true
        verbose: true

-   repo: local
    hooks:
    -   id: docs
        name: Build docs
        entry: "scripts/build-docs-pre-commit.sh"
        language: python
        language_version: python3.10
        files: ^docs
        require_serial: true
        verbose: true

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json
