blank_issues_enabled: true

contact_links:
  - name: Security Contact
    about: Please report security vulnerabilities to support@ag2.ai
  - name: Question or Problem
    about: Ask a question or ask about a problem in GitHub Discussions.
    url: https://github.com/ag2ai/faststream/discussions/categories/questions
