name: Check docs for broken links

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

jobs:
  check-broken-link:
    name: Check docs for broken links
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check links using container
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://faststream.airt.ai
          cmd_params: '--buffer-size=8192 --max-connections=1 --color=always --header="User-Agent:Mozilla/5.0(Firefox/97.0)" --exclude="(localhost:8000|linkedin.com|fonts.gstatic.com|reddit.com)" --max-connections-per-host=1 --rate-limit=1'
          debug: true
