name: Check docs for broken links

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]
  push:

jobs:
  check-broken-link:
    name: Check docs for broken links
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check links using container
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://faststream.airt.ai
          cmd_params: '--verbose --buffer-size=8192 --max-connections=10 --color=always --exclude="(localhost:8000|linkedin.com|fonts.gstatic.com|docker.com)"'
          debug: true
