name: Dependabot automerge

on:
  pull_request_target:

jobs:
  automerge:
    name: Enable pull request automerge
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          merge-method: REBASE

  autoapprove:
    name: Automatically approve pull request
    needs: [automerge]
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
