name: Index docs for fastkafka chat application

on:
  workflow_run:
    workflows: ["pages-build-deployment"]
    types: [completed]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  on-success:
    name: Index docs for fastkafka chat application
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout airtai/fastkafkachat repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.head_ref }}
          repository: airtai/fastkafkachat

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: settings.ini

      - name: Install Dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          test -f setup.py && pip install -e ".[dev]"

      - name: Index the fastkafka docs
        shell: bash
        run: |
          index_website_data

      - name: Push updated index to airtai/fastkafkachat repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update fastkafka docs index file"
          file_pattern: "data/website_index.zip"
