name: CI
on:  [workflow_dispatch, pull_request, push]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os:  [ubuntu]
        version: ["3.7", "3.8", "3.9", "3.10"]
    runs-on: ${{ matrix.os }}-latest
    env:
      # Used in notebooks for testing
      KAFKA_HOSTNAME: "localhost"
      KAFKA_PORT: "9092"
    defaults:
      run:
        shell: bash
    services:
      zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - 2181:2181
          - 2888:2888
          - 3888:3888
      kafka:
        image: wurstmeister/kafka
        env:
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_LISTENERS: "PLAINTEXT://:9092"
          KAFKA_CREATE_TOPICS: "training_request:1:1,training_status:1:1,prediction_request:1:1,prediction_status:1:1"
          KAFKA_ADVERTISED_HOST_NAME: "localhost"
        ports:
          - 9092:9092
    steps:
      - name: Install quarto
        run: |
          wget -q https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
      - name: Setup node
        run: | 
          sudo curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          sudo apt-get install -y nodejs
          sudo apt purge --auto-remove
          sudo apt clean && rm -rf /var/lib/apt/lists/*
 #     - uses: actions/setup-node@v3
 #       with:
 #         node-version: 18
      - name: Check npx
        run: npx --version
      - name: Run nbdev tests
        uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}
      - name: Test building docs with nbdev-mkdocs
        run: |
          test -f setup.py && pip install -e ".[dev]"
          nbdev_mkdocs docs
          if [ -f "mkdocs/site/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la mkdocs/site/
            exit 1
          fi
