name: CI
on:  [workflow_dispatch, push]

jobs:
  mypy_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-mypy-check@main
  bandit_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-bandit-check@main
  semgrep_static_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: airtai/workflows/airt-semgrep-check@main
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:  [ubuntu]
        version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Install quarto
        run: |
          wget -q https://www.quarto.org/download/latest/quarto-linux-amd64.deb
          sudo dpkg -i quarto-linux-amd64.deb
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
      - name: Prepare nbdev env
        uses: fastai/workflows/nbdev-ci@master
        with:
          version: ${{ matrix.version }}
          skip_test: true
      - name: Install testing deps
        run: |
          y | fastkafka docs install_deps
          fastkafka testing install_deps
      - name: Run nbdev tests
        run: |
          nbdev_test
      - name: Test building docs with nbdev-mkdocs
        run: |
          nbdev_mkdocs docs
          if [ -f "mkdocs/site/index.html" ]; then
            echo "docs built successfully."
          else
            echo "index page not found in rendered docs."
            ls -la
            ls -la mkdocs/site/
            exit 1
          fi
